language: python
python:
  - '2.7'
install: pip install -r requirements.txt --use-mirrors
script: nosetests -v --with-coverage --cover-package=mailstat --cover-inclusive --cover-erase tests
notifications:
  email:
    recipients:
      - benjamin@bengfort.com
    on_success: change
    on_failure: always
